# This file is the configuration file that set up the build enviroment. 
# You can find a template of this file in the template folder
---

#name of the app
app_name: codefaces

# Setting the paths for fetch, build and package 
environment:
  # source_dir is the directory where the source code is fetched from the 
  # repository
  source_dir: build/src
  
  # tool_dir is the directory where the eclipse build tools and 
  # depended pre-built libraries are fetched
  tool_dir: build/tool

  # build_dir is the directory where the code is compiled
  build_dir: build/bin
  
  # package_dir is the directory where the compiled code is packaged and ready 
  # to be deployed
  package_dir: build/package

# Setting the fetching repository
fetch:
  - description: codefaces main repository
    scm: git
    branch: master
    repository: "git@github.com:jingweno/code_faces.git"
      
tools:
  eclipse_platform:
    description: Eclipse Platfrom
    name: eclipse-rcp-galileo-SR2-macosx-cocoa.tar.gz
    scm: http
    unpack: true
    repository: "http://mirror.csclub.uwaterloo.ca/eclipse/technology/epp/downloads/release/galileo/SR2/eclipse-rcp-galileo-SR2-macosx-cocoa.tar.gz"
  
  target_platform:
    description: repository for RAP target platform
    name: "rap-runtime-1.3.0-RC4-20100608-1549.zip"
    scm: http
    repository: "http://mirror.csclub.uwaterloo.ca/eclipse/rt/rap/1.3/rap-runtime-1.3.0-RC4-20100608-1549.zip" 

  servlet_bridge:
    - description: Equinox servletbridge
      name: org.eclipse.equinox.servletbridge_1.2.0.v20100503.jar
      scm: http 
      repository: "http://mirror.csclub.uwaterloo.ca/eclipse/equinox/drops/S-3.6RC4-201006031500/org.eclipse.equinox.servletbridge_1.2.0.v20100503.jar"
    
    - description: Equinox http servletbridge
      name: org.eclipse.equinox.http.servletbridge_1.0.200.v20100503.jar
      scm: http
      repository: "http://mirror.csclub.uwaterloo.ca/eclipse/equinox/drops/S-3.6RC4-201006031500/org.eclipse.equinox.http.servletbridge_1.0.200.v20100503.jar"

  compressor:
    description: YUI compressor
    name: yuicompressor-2.4.2.zip
    scm: http
    unpack: true
    repository: "http://yuilibrary.com/downloads/yuicompressor/yuicompressor-2.4.2.zip"

# Setting the build environment
build:
  
  # compress files
  files_to_compress:
    - org.codefaces.web/public/stylesheets
    - org.codefaces.web/public/welcome.html

  # template path
  build_template_dir: template/build
  
  # The folder containing the finished build.
  # It will be inside the build_dir/build directory
  build_label: build_result

  # the eclipse project name of the codefaces feature 
  codefaces_feature: org.codefaces.feature
  
  # The path of the build.porperties file template
  build_properties_path: templates/buildConfig/build.properties
  
  # Jave source version
  java_src_version: 1.6
  
  # Java target version
  java_target_version: 1.6
  
# Settings for packaging
package:
  # The path of the WAR archive template
  war_template_path: templates/war
